name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        arch: [x86, x86_64]
        include:
          - os: windows-latest
            arch: x86
            os_short: win
            compiler_cc: msvc
            rust-target: i686-pc-windows-msvc
            packaging: Compress-Archive -Path ./package/* -DestinationPath timerex-win-x86.zip
          - os: windows-latest
            arch: x86_64
            os_short: win
            compiler_cc: msvc
            rust-target: x86_64-pc-windows-msvc
            packaging: Compress-Archive -Path ./package/* -DestinationPath timerex-win-x86_64.zip
          - os: ubuntu-22.04
            arch: x86
            os_short: linux
            compiler_cc: clang
            compiler_cxx: clang++
            rust-target: i686-unknown-linux-musl
            packaging: cd package && zip -r ../timerex-linux-x86.zip addons
          - os: ubuntu-22.04
            arch: x86_64
            os_short: linux
            compiler_cc: clang
            compiler_cxx: clang++
            rust-target: x86_64-unknown-linux-musl
            packaging: cd package && zip -r ../timerex-linux-x86_64.zip addons
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os_short }}-${{ matrix.compiler_cc }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          path: timerex

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.rust-target }}
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: timerex

      - uses: actions/checkout@v4
        name: Checkout sourcemod
        with:
          repository: alliedmodders/sourcemod
          submodules: recursive
          path: sourcemod

      - uses: actions/checkout@v4
        name: Checkout metamod-source
        with:
          repository: alliedmodders/metamod-source
          path: mmsource

      - uses: actions/checkout@v4
        name: Checkout ambuild
        with:
          repository: alliedmodders/ambuild
          path: ambuild

      # Setup Python for AMBuild
      - uses: actions/setup-python@v5
        name: Setup Python 3.13
        with:
          python-version: 3.13
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install ambuild
        run: pip install ./ambuild

      - name: Install Linux 64-bit dependencies
        if: startsWith(runner.os, 'Linux') && matrix.arch == 'x86_64'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libstdc++6 libc6-dev linux-libc-dev \
            ${{ matrix.compiler_cc }}

      - name: Install Linux 32-bit dependencies
        if: startsWith(runner.os, 'Linux') && matrix.arch == 'x86'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            gcc-multilib g++-multilib libstdc++6 lib32stdc++6 \
            libc6-dev libc6-dev-i386 linux-libc-dev linux-libc-dev:i386 \
            lib32z1-dev ${{ matrix.compiler_cc }}

      - name: Select clang compiler
        if: startsWith(runner.os, 'Linux')
        run: |
          echo "CC=${{ matrix.compiler_cc }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.compiler_cxx }}" >> $GITHUB_ENV
          ${{ matrix.compiler_cc }} --version
          ${{ matrix.compiler_cxx }} --version

      - name: Build
        working-directory: timerex
        run: |
          cargo build --target ${{ matrix.rust-target }} --release
          mkdir -p build && cd build
          python ../configure.py --enable-optimize --sm-path=${{ github.workspace }}/sourcemod/ --mms-path=${{ github.workspace }}/mmsource/ --targets ${{ matrix.arch }}
          ambuild
          ${{ matrix.packaging }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: timerex/build/timerex-${{ matrix.os_short }}-${{ matrix.arch }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
